name: build

on: 
  push:
    branches:
      - "**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: prometheus-auth
  MTR_REPO: mtr.devops.telekom.de/caas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to MTR
        uses: docker/login-action@v3
        with:
          registry: mtr.devops.telekom.de
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
              ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
              ${{ env.MTR_REPO }}/${{env.IMAGE_NAME}}
          tags: |
            type=semver,pattern={{version}}
            type=sha
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
      - name: Sign container images with a key
        uses: dodopizza/cosign-sign-push-action@v1.0.13
        # only run when a tag is pushed
        if: startsWith(github.ref, 'refs/tags/')
        with:
          image-tags: ${DOCKER_METADATA_OUTPUT_TAGS}
          image-digest: ${{ steps.build-and-push.outputs.digest }}
          cosign-private-key: ${{ secrets.COSIGN_KEY }}
          cosign-password: ""
