name: build

on: push

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: prometheus-auth
  IMAGE_TAG: ${{ github.sha }}
  MTR_REPO: mtr.devops.telekom.de/caas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to MTR
        uses: docker/login-action@v3
        with:
          registry: mtr.devops.telekom.de
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/$${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}, ${{ env.MTR_REPO }}/${{env.IMAGE_NAME}}:${{ env.IMAGE_TAG }}
        env:
          IMAGE: prometheus-auth
          MTR: mtr.devops.telekom.de
          REPO: caas/prometheus-auth
      - name: Sign container images with a key
        uses: dodopizza/cosign-sign-push-action@v1.0.13
        with:
          image-tags: ghcr.io/${{ github.repository_owner }}/${IMAGE}/${IMAGE}:${VERSION}
          image-digest: ${{ steps.build-and-push.outputs.digest }}
          cosign-private-key: ${{ secrets.COSIGN_KEY }}
          cosign-password: ""
